import 'units.dart';

/// What a block of bubbles encodes.
enum BlockType {
  /// Single/multi-correct MCQ rows: one field per question, options A..n.
  mcq,

  /// Integer answer digit grid: one field per digit position, options 0–9
  /// stacked vertically.
  intDigits,

  /// Roll number: identical geometry to [BlockType.intDigits]; the reader
  /// additionally enforces exactly-one-mark-per-column and roster validation.
  rollDigits,

  /// Answer-set code (A/B/C/D): a single field.
  setCode,

  /// Matrix/list-match rows (reserved; v1 presets do not emit it).
  matrix,
}

/// Which way fields advance; the option axis is the other one.
enum BlockDirection {
  /// Fields (questions) stack vertically, options run horizontally — MCQ rows.
  vertical,

  /// Fields (digit positions) advance horizontally, options 0–9 stack
  /// vertically — digit grids.
  horizontal,
}

/// A block of bubbles generated by PURE ADDITION from origin + two pitches.
/// No per-bubble coordinates are ever authored or stored — the block extent
/// is computed, which is what makes the additive format typo-resistant.
class FieldBlock {
  const FieldBlock({
    required this.blockId,
    required this.blockType,
    required this.originMm,
    required this.bubblePitchMm,
    required this.rowPitchMm,
    required this.direction,
    this.options = 4,
    this.bubbleValues,
    this.fieldLabels = const [],
  });

  final String blockId;
  final BlockType blockType;

  /// Centre of the FIRST bubble (top-left-most) in mm.
  final MmPoint originMm;

  /// Centre-to-centre pitch along the OPTION axis, mm.
  final double bubblePitchMm;

  /// Centre-to-centre pitch along the FIELD axis, mm.
  final double rowPitchMm;

  final BlockDirection direction;

  /// Option count per field (4/5 for MCQ, 10 for digit grids).
  final int options;

  /// Explicit option values (defaults per type: A.. for mcq/setCode, 0..9 for
  /// digit grids).
  final List<String>? bubbleValues;

  /// Field labels, range-expandable ("q1..q30" -> q1, q2, ..., q30).
  final List<String> fieldLabels;

  /// Expanded option values for this block's type.
  List<String> get optionValues => bubbleValues ??
      switch (blockType) {
        BlockType.mcq ||
        BlockType.setCode ||
        BlockType.matrix =>
          [for (var i = 0; i < options; i++) String.fromCharCode(65 + i)],
        BlockType.intDigits || BlockType.rollDigits => [for (var i = 0; i < 10; i++) '$i'],
      };

  /// Expanded field labels — also each field's global key (q17, roll3, set).
  List<String> get fields => expandLabels(fieldLabels);

  /// Centre of the bubble for [fieldIndex], [optionIndex], in mm.
  MmPoint bubbleCenter(int fieldIndex, int optionIndex) => switch (direction) {
        BlockDirection.vertical => MmPoint(
            originMm.x + optionIndex * bubblePitchMm,
            originMm.y + fieldIndex * rowPitchMm,
          ),
        BlockDirection.horizontal => MmPoint(
            originMm.x + fieldIndex * rowPitchMm,
            originMm.y + optionIndex * bubblePitchMm,
          ),
      };

  /// Full extent covering every bubble outline (bubble half-sizes included).
  /// [bubbleW]/[bubbleH] come from the sheet's BubbleStyle.
  MmRect extentMm({required double bubbleW, required double bubbleH}) {
    final nFields = fields.length;
    final nOptions = options;
    final (spanFields, spanOptions) = switch (direction) {
      BlockDirection.vertical => (
          (nFields - 1) * rowPitchMm + bubbleH,
          (nOptions - 1) * bubblePitchMm + bubbleW
        ),
      BlockDirection.horizontal => (
          (nFields - 1) * rowPitchMm + bubbleW,
          (nOptions - 1) * bubblePitchMm + bubbleH
        ),
    };
    return switch (direction) {
      BlockDirection.vertical => MmRect(
          originMm.x - bubbleW / 2,
          originMm.y - bubbleH / 2,
          spanOptions,
          spanFields,
        ),
      BlockDirection.horizontal => MmRect(
          originMm.x - bubbleW / 2,
          originMm.y - bubbleH / 2,
          spanFields,
          spanOptions,
        ),
    };
  }

  Map<String, Object?> toJson() => {
        'blockId': blockId,
        'blockType': blockType.name,
        'originMm': [originMm.x, originMm.y],
        'bubblePitchMm': bubblePitchMm,
        'rowPitchMm': rowPitchMm,
        'direction': direction.name,
        'options': options,
        if (bubbleValues != null) 'bubbleValues': bubbleValues,
        'fieldLabels': fieldLabels,
      };

  static FieldBlock fromJson(Map<String, Object?> j) => FieldBlock(
        blockId: j['blockId']! as String,
        blockType: BlockType.values.byName(j['blockType']! as String),
        originMm: MmPoint(
          ((j['originMm']! as List).first as num).toDouble(),
          ((j['originMm']! as List).last as num).toDouble(),
        ),
        bubblePitchMm: (j['bubblePitchMm']! as num).toDouble(),
        rowPitchMm: (j['rowPitchMm']! as num).toDouble(),
        direction: BlockDirection.values.byName(j['direction']! as String),
        options: j['options'] as int? ?? 4,
        bubbleValues: (j['bubbleValues'] as List<Object?>?)?.cast<String>(),
        fieldLabels: (j['fieldLabels']! as List<Object?>).cast<String>(),
      );
}

/// Expands label ranges: 'q1..q30' -> q1..q30 (numeric zero-padded to the
/// widest), plain tokens pass through. Order is preserved.
List<String> expandLabels(List<String> labels) {
  final out = <String>[];
  for (final label in labels) {
    final m = RegExp(r'^(\D*)(\d+)\.\.(\D*)(\d+)$').firstMatch(label);
    if (m == null) {
      out.add(label);
      continue;
    }
    final p1 = m.group(1)!;
    final p2 = m.group(3)!;
    if (p1 != p2) {
      throw FormatException('Range prefix mismatch in "$label"');
    }
    final start = int.parse(m.group(2)!);
    final end = int.parse(m.group(4)!);
    if (end < start) {
      throw FormatException('Descending range in "$label"');
    }
    final width = m.group(2)!.length;
    for (var i = start; i <= end; i++) {
      out.add('$p1${i.toString().padLeft(width, '0')}');
    }
  }
  return out;
}
